# Python package
trigger:
- main

pool:
  name: Default

variables:
  PYTHON_PATH: 'C:\Users\shravani.banda\AppData\Local\Programs\Python\Python313\python.exe'

steps:
- script: |
    "$(PYTHON_PATH)" -m pip install --upgrade pip
    "$(PYTHON_PATH)" -m pip install -r requirements.txt
    "$(PYTHON_PATH)" -m pip install pytest pytest-azurepipelines
    "$(PYTHON_PATH)" -m pytest
  displayName: 'Install dependencies and run tests'