# Python package
trigger:
- main

pool:
  name: Default  # Using Default pool for self-hosted agent

steps:
# Removing UsePythonVersion task since we'll use local Python

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'Install dependencies and run tests'