trigger:
- main

pool:
  name: Default

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # Choose the required Python version
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    python -m pip install -r requirements.txt
    python -m pip install pytest pytest-azurepipelines
    python -m pytest
  displayName: 'Install dependencies and run tests'