trigger:
- main

pool:
  name: Default  # Ensure this is a self-hosted Windows agent

steps:
- task: CmdLine@2
  inputs:
    script: |
      echo Hello, World! > "C:\Users\shravani.banda\Desktop\hello.txt"
  displayName: 'Create hello.txt on Desktop'
