# Python package
trigger:
- main

pool:
  name: Default  # Using Default pool for self-hosted agent

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.13.0'
  displayName: 'Use Python 3.13.0'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'Install dependencies and run tests'